---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webhook.operators.coreos.io
  resources:
  - webhooktests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.operators.coreos.io
  resources:
  - webhooktests/finalizers
  verbs:
  - update
- apiGroups:
  - webhook.operators.coreos.io
  resources:
  - webhooktests/status
  verbs:
  - get
  - patch
  - update
